'use strict';
const schedule = {
 9: {title:'Chegar. Respirar. Olhar para cima.',intro:'Sexta-feira · Instalar-se em Sapucaí-Mirim e manter o primeiro dia leve.',items:[['Tarde','Chegada & centrinho','Check-in, uma caminhada no centro e uma compra de lanches para os próximos dias.'],['Fim da tarde','Mirante do Cruzeiro','Consulte o acesso com a hospedagem e aproveite a luz do fim do dia.'],['Jantar','Uma refeição combinada','Confirme a adaptação vegana no Panela Mineira ou na Cantina da Lurdinha.'],['Noite','Primeira chance de Via Láctea','Se o céu estiver limpo, use um ponto reconhecido de dia próximo à hospedagem.','#estrelas']]},
 10: {title:'Água corrente e uma pausa vegana.',intro:'Sábado · Cachoeira de manhã; São Bento à tarde. Sem colecionar todos os passeios no mesmo dia.',items:[['Manhã','Cachoeira da Amizade','Comece pela opção próxima ao centro. Ponte Nova ou Posses são alternativas, com acesso e clima confirmados.','#lugares'],['Almoço','Refeição vegana confirmada','Combine o almoço antes da saída ou leve um piquenique. A confeitaria da tarde não substitui um almoço reservado.'],['14h–17h','São Bento & La Gorda Vegana','Passeio curto no centro e pausa para café, doces ou lanche. Confirme o funcionamento.','#vegano'],['Noite','Lua Nova, sessão principal','Volte com tempo de reconhecer o horizonte e montar a câmera ao entardecer. Priorize a noite se a previsão estiver boa.','#estrelas']]},
 11: {title:'Um domingo entre as montanhas.',intro:'Domingo · Bauzinho como passeio principal. Pedra da Mata é uma troca possível, não uma obrigação extra.',items:[['Manhã','Bauzinho & vista da Pedra do Baú','Consulte as regras de acesso. Para subir ao Baú, troque o passeio por uma atividade técnica previamente agendada.','#lugares'],['Almoço','São Bento do Sapucaí','Reserve uma refeição com preparo vegano confirmado. Não conte com a La Gorda, cujo horário listado não inclui domingo.','#vegano'],['Tarde','Centro & descanso','Uma caminhada curta, artesanato e retorno à hospedagem. Alternativa ao dia de Baú: Pedra da Mata com autorização.'],['Noite','Última chance de céu escuro','Repita o melhor ponto das noites anteriores ou ajuste o enquadramento. O céu decide.','#estrelas']]},
 12: {title:'Mais um café. Depois, a estrada.',intro:'Segunda-feira · Feriado de Nossa Senhora Aparecida. Deixe margem para o retorno.',items:[['Manhã','Café & passeio leve','Curta a hospedagem ou o centrinho. Uma trilha só entra se houver tempo de sobra e condições boas.'],['Antes de sair','Lanche para a viagem','Garanta comida vegana para o caminho e confira os itens da câmera.'],['Retorno','Check-out sem pressa','Planeje o trânsito de feriado e ajuste a saída à distância até sua casa.']]}
};
const tabs=[...document.querySelectorAll('[role=tab]')];
function renderDay(key){const day=schedule[key];tabs.forEach(t=>{const active=t.dataset.day===String(key);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1});const panel=document.querySelector('#day-panel');panel.setAttribute('aria-labelledby','tab-'+key);panel.replaceChildren();const heading=document.createElement('div');heading.className='day-heading';const h=document.createElement('h3');h.textContent=day.title;const intro=document.createElement('p');intro.textContent=day.intro;heading.append(h,intro);const list=document.createElement('ol');list.className='timeline';day.items.forEach(([time,title,description,href])=>{const li=document.createElement('li');const label=document.createElement('span');label.textContent=time;label.style.fontSize='.8rem';label.style.color='var(--muted)';const content=document.createElement('div');const b=document.createElement('b');if(href){const a=document.createElement('a');a.href=href;a.textContent=title;b.append(a)}else b.textContent=title;const p=document.createElement('p');p.textContent=description;content.append(b,p);li.append(label,content);list.append(li)});panel.append(heading,list)}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>renderDay(t.dataset.day));t.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();renderDay(tabs[next].dataset.day);tabs[next].focus()}})});renderDay(9);
const places=JSON.parse(document.querySelector('#place-data').textContent);
const dialog=document.querySelector('#place-dialog');let lastTrigger;
document.querySelectorAll('[data-place]').forEach(button=>button.addEventListener('click',()=>{const place=places.find(p=>p.id===button.dataset.place);lastTrigger=button;document.querySelector('#dialog-city').textContent=place.city;document.querySelector('#dialog-title').textContent=place.title;document.querySelector('#dialog-description').textContent=place.details;document.querySelector('#dialog-map').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place.map);document.querySelector('#dialog-source').href=place.source;dialog.showModal()}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});dialog.addEventListener('close',()=>lastTrigger?.focus());
document.querySelector('#night-mode').addEventListener('click',e=>{const dim=document.body.classList.toggle('dim');e.currentTarget.setAttribute('aria-pressed',String(dim));e.currentTarget.textContent=dim?'Desativar luz baixa':'Ativar luz baixa'});
