'use strict';
const schedule = {
 9: {title:'Chegada ao Juncal & primeira noite',intro:'Sexta-feira · Chegar com luz e conhecer a base.',items:[['Tarde','Check-in & compras','Chegue com luz do dia; check-in das 14h às 22h. Compre alimentos e bebidas no caminho. O chalé fica perto de Gonçalves, não do centro de Sapucaí-Mirim.','#base'],['Fim da tarde','Reconhecer o entorno','Veja o espaço seguro para tripé, as árvores e o horizonte oeste/sudoeste. Combine com a anfitriã acesso e iluminação. O Mirante do Cruzeiro fica como opção para uma saída ao centro, não como compromisso na chegada.','#base'],['Jantar','Cozinha do chalé','Prepare uma refeição vegana e os lanches da noite. Restaurantes do roteiro só entram com ingredientes, horário e deslocamento confirmados.','#vegano'],['Noite','Primeira chance de Via Láctea','Se houver céu aberto e um ponto adequado autorizado, fotografe perto da base. Não dependa de dirigir por estrada desconhecida depois de escurecer.','#estrelas']]},
 10: {title:'Passeios por perto & Lua Nova',intro:'Sábado · Pouco deslocamento para priorizar a fotografia.',items:[['Manhã','Cachoeira ou trilha próxima','A anfitriã informa cachoeira a 5 minutos e trilha atrás da propriedade. Confirme o acesso e se o tempo indicado é a pé ou de carro. São opções diferentes das cachoeiras do centro.','#base'],['Almoço','Piquenique ou almoço no chalé','A cozinha facilita uma refeição vegana. Um passeio curto por Gonçalves é opcional; confirme alimentação antes de sair.','#base'],['Tarde','Descanso & preparação','Teste as câmeras e reconheça o ponto antes de escurecer. Pedra do Jair, no Juncal, é uma alternativa de visita diurna com acesso confirmado; não um local noturno garantido.','#lugares'],['Noite','Lua Nova, sessão principal','Leve tripé, cadeira, lanche, casaco e lanterna vermelha. Priorize esta noite se o céu estiver aberto e mantenha o retorno combinado.','#estrelas']]},
 11: {title:'Uma saída opcional & mais uma noite',intro:'Domingo · Escolha São Bento ou Sapucaí-Mirim; preserve tempo para voltar com luz.',items:[['Manhã','Bauzinho ou passeio em Sapucaí','Se escolherem São Bento, priorizem Bauzinho; Ana Chata requer preparo e agendamento. Alternativa: Amizade e uma entre Posses/Ponte Nova em Sapucaí-Mirim. Confirme as rotas desde o Juncal; as distâncias citadas nos cards partem dos centros das cidades.','#lugares'],['Almoço','Refeição no destino escolhido','São Bento: Entre Vilas ou Brazin com reserva/ingredientes confirmados. Sapucaí-Mirim: Panela Mineira ou Cantina com preparo vegano combinado. Não conte com nenhuma opção sem confirmação.','#vegano'],['Tarde','Retorno com luz & descanso','Evite acumular cachoeiras e Baú no mesmo dia. Confira estrada e tempo de retorno no mapa privado da reserva antes de sair. La Gorda só entra com abertura confirmada.','#base'],['Noite','Via Láctea ou jantar','Se sábado fechar, domingo ganha prioridade para fotografia: reduza ou troque a saída diurna. Bentô continua como alternativa de jantar em São Bento, se preferirem ficar na cidade e tiverem retorno planejado.','#estrelas']]},
 12: {title:'Passeio próximo & check-out',intro:'Segunda-feira · Desocupar o chalé até 12h.',items:[['Manhã','Café & passeio curto','Prefira a trilha ou cachoeira próxima com acesso confirmado, deixando tempo para arrumar as malas. Pedra da Mata fica como alternativa após o check-out, se a rota de retorno e as 2–3 h de trilha couberem.','#base'],['Até 12h','Check-out do chalé','Confira câmera, baterias e cartões. Feche as janelas, tranque o chalé e leve o lixo às lixeiras indicadas.','#base'],['Depois','Almoço & estrada','Garanta uma refeição vegana ou lanches para a viagem. Ajuste o retorno ao trânsito de feriado; uma trilha distante é opcional, não parte obrigatória deste dia.','#vegano']]}

};
const tabs=[...document.querySelectorAll('[role=tab]')];
function renderDay(key){
 const day=schedule[key];
 tabs.forEach(t=>{const active=t.dataset.day===String(key);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1});
 const panel=document.querySelector('#day-panel');panel.setAttribute('aria-labelledby','tab-'+key);panel.replaceChildren();
 const heading=document.createElement('h3');heading.className='day-heading';heading.textContent=day.title;panel.append(heading);
 const list=document.createElement('ol');list.className='timeline';
 day.items.forEach(([time,title,description,href])=>{
  const li=document.createElement('li');if(time==='Noite')li.className='night-event';
  const details=document.createElement('details');const summary=document.createElement('summary');
  const label=document.createElement('span');label.className='time-label';label.textContent=time;
  const name=document.createElement('strong');name.textContent=title;const plus=document.createElement('span');plus.className='plus';plus.textContent='＋';plus.setAttribute('aria-hidden','true');summary.append(label,name,plus);
  const content=document.createElement('div');content.className='detail-content';const text=document.createElement('p');text.textContent=description;content.append(text);
  if(href){const a=document.createElement('a');a.href=href;a.textContent=href==='#estrelas'?'Abrir guia da noite':href==='#vegano'?'Ver opções de comida':'Ver lugares e mapas';content.append(a)}
  details.append(summary,content);li.append(details);list.append(li);
 });panel.append(list);
}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>renderDay(t.dataset.day));t.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();renderDay(tabs[next].dataset.day);tabs[next].focus()}})});renderDay(9);
const places=JSON.parse(document.querySelector('#place-data').textContent);const dialog=document.querySelector('#place-dialog');let lastTrigger;
document.querySelectorAll('[data-place]').forEach(button=>button.addEventListener('click',()=>{
 const place=places.find(p=>p.id===button.dataset.place);lastTrigger=button;
 document.querySelector('#dialog-city').textContent=place.city;document.querySelector('#dialog-title').textContent=place.title;document.querySelector('#dialog-description').textContent=place.details;
 const settings=document.querySelector('#dialog-settings');settings.replaceChildren(); (place.settings||[]).forEach(([label,value])=>{const cell=document.createElement('div');const key=document.createElement('small');key.textContent=label;const val=document.createElement('strong');val.textContent=value;cell.append(key,val);settings.append(cell)}); const links=document.querySelector('#dialog-links');links.replaceChildren();
 const items=place.links||[{url:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place.map),label:'Abrir no mapa'},{url:place.source,label:'Consultar fonte'}];
 items.forEach((item,i)=>{const a=document.createElement('a');a.href=item.url;a.textContent=item.label;a.target='_blank';a.rel='noopener noreferrer';a.className='button '+(i===0?'primary':'secondary');links.append(a)});
 dialog.showModal();document.querySelector('#close-dialog').focus();
}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});dialog.addEventListener('close',()=>lastTrigger?.focus());
document.querySelector('#night-mode').addEventListener('click',e=>{const dim=document.body.classList.toggle('dim');e.currentTarget.setAttribute('aria-pressed',String(dim));e.currentTarget.setAttribute('aria-label',dim?'Desativar luz baixa':'Ativar luz baixa');document.querySelector('#mode-label').textContent=dim?'Luz normal':'Luz baixa'});
const navLinks=[...document.querySelectorAll('.bottom-nav a')];
const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){navLinks.forEach(a=>{if(a.hash==='#'+entry.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}}},{rootMargin:'-15% 0px -60% 0px'});
['estrelas','roteiro','lugares','vegano'].forEach(id=>observer.observe(document.getElementById(id)));
